name: duolingo
version: '1.0.0'
config-version: 2

profile: duolingo

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
seed-paths: ["seeds"]

models:
  duolingo:
    staging:
      +materialized: table
      +schema: staging
    marts:
      +materialized: table
      +schema: marts