id: pipeline_master
namespace: duolingo

triggers:
  - id: yearly_run
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 0 10 1 *"
    timezone: "America/New_York"
    concurrency:
      limit: 1

tasks:

  - id: gcp_kv
    type: io.kestra.plugin.core.flow.Subflow
    namespace: duolingo
    flowId: gcp_kv
    wait: true

  - id: gcp_setup
    type: io.kestra.plugin.core.flow.Subflow
    namespace: duolingo
    flowId: gcp_setup
    wait: true

  - id: ingestion
    type: io.kestra.plugin.core.flow.Subflow
    namespace: duolingo
    flowId: ingestion
    wait: true

  - id: table_creation
    type: io.kestra.plugin.core.flow.Subflow
    namespace: duolingo
    flowId: table_creation
    wait: true

  - id: dbt_transform
    type: io.kestra.plugin.core.flow.Subflow
    namespace: duolingo
    flowId: dbt_transform
    wait: true